### ISSUE TITLE
Can't declare domain-models outside of package "com.axelor"

### ISSUE THREAD

**Issue by anthony-o** [axelor/axelor-development-kit#16]
If in my `domain-models` I'm using

```xml
<module name="mymodule" package="com.mycompany.mymodule.db"/>
```

Then it is not taken into account : my `Entity` is not discovered at runtime.

If I have only one `domain-model` using such a package, then when booting at first time, I have that exception :

```
2014-12-02 14:47:11,972 [localhost-startStop-1] INFO  com.axelor.meta.loader.ModelLoader - importing model: MyType
2014-12-02 14:47:11,975 [localhost-startStop-1] ERROR com.axelor.web.InitServlet - 
java.lang.NullPointerException
	at com.axelor.meta.service.MetaModelService.process(MetaModelService.java:79)
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:58)
	at com.axelor.meta.loader.ModelLoader.importModels(ModelLoader.java:119)
	at com.axelor.meta.loader.ModelLoader.doLoad(ModelLoader.java:69)
	at com.axelor.meta.loader.AbstractLoader.load(AbstractLoader.java:154)
	at com.axelor.meta.loader.ModuleManager.installMeta(ModuleManager.java:274)
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
	at com.axelor.meta.loader.ModuleManager.install(ModuleManager.java:257)
	at com.axelor.meta.loader.ModuleManager.install(ModuleManager.java:240)
	at com.axelor.meta.loader.ModuleManager.initialize(ModuleManager.java:110)
	at com.axelor.web.InitServlet.init(InitServlet.java:50)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:117)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:102)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:172)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4809)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5485)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

This is because `MetaModelService.process(Class<?> klass)` is called with `null`, called by `ModelLoader.importModels(Document doc, URL file, boolean update)` which executes `service.process(JPA.model(name));` which calls `JpaScanner.findModel(name)` which returns `null`.

**Comment by pbe-axelor** [comment]
We are using classpath scanning to dynamically search for web services and domain classes.
To speed up the scan, domain classes started with `com.axelor` and web service started with `com.axelor.web` are accepted.

We plan to have the ability to set a list of packages to scan in a next version.

**Comment by mea-axelor** [comment]
Fixed in dev branch for upcoming v4 release.

The `<module>` tag is changed like this:

```xml
<!-- required -->
<module name="contact" package="com.axelor.contact.db" />

<!-- default (backwards compatible) -->
<module name="contact" package="com.axelor.contact.db"  repo-package="com.axelor.contact.db.repo" table-prefix="contact" />

<!-- user controlled -->
<module name="contact" package="my.models"  repo-package="my.repos" table-prefix="my" />
```
