### ISSUE TITLE
Main branch 4.0 , issue with java.lang.StackOverflowError

### ISSUE THREAD

**Issue by marioestradarosa** [axelor/axelor-development-kit#28]
./gradlew tomcatRun on new project with one simple module, raises  the following exception.

* What went wrong:
A problem occurred configuring root project 'prueba'.
> Failed to notify project evaluation listener.
   > java.lang.StackOverflowError (no error message)

A stacktrace shows...
* Exception is
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'prueba'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
	... 44 more
Caused by: java.lang.StackOverflowError
	at com.axelor.gradle.tasks.GenerateCode._findAllModules(GenerateCode.groovy:56)
	at com.axelor.gradle.tasks.GenerateCode$__findAllModules_closure3.doCall(GenerateCode.groovy:59)
	at com.axelor.gradle.tasks.GenerateCode._findAllModules(GenerateCode.groovy:56)

**Comment by marioestradarosa** [comment]
The problem was raised due to an infinite recursive, the module was named like the application so by removing the module and creating a new one with another name solved the problem.
