### ISSUE TITLE
ADK 4.0 REST Services : NullPointerException

### ISSUE THREAD

**Issue by mrp14** [axelor/axelor-development-kit#32]
Hello,

I'm trying to use ADK REST Services in order to develop a client app. 
I'm getting a NullPointerException when I try to retrieve a records list : 

Example query : 

`GET /ws/rest/com.axelor.auth.db.User`

Response => 

> java.lang.NullPointerException
> at com.axelor.rpc.Criteria.parse(Criteria.java:79)
> at com.axelor.rpc.Request.getCriteria(Request.java:147)
> at com.axelor.rpc.Resource.getCriteria(Resource.java:278)
> at com.axelor.rpc.Resource.getQuery(Resource.java:282)
> at com.axelor.rpc.Resource.search(Resource.java:311)
> at com.axelor.rpc.ResponseInterceptor.invoke(ResponseInterceptor.java:54)
> at com.axelor.web.service.RestService.find(RestService.java:124)
> at com.axelor.rpc.ResponseInterceptor.invoke(ResponseInterceptor.java:63)
> at sun.reflect.GeneratedMethodAccessor180.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
...`

While, if I try to get only one record, I successfully get data : 

`GET /ws/rest/com.axelor.auth.db.User/1`

Response => 

```
{
   "status":0,
   "data":[
      {
         "code":"admin",
         "updatedBy":{
            "code":"admin",
            "name":"Administrator",
            "id":1,
            "$version":2
         },
         "roles":[

         ],
         "singleTab":false,
         "metaPermissions":[

         ],
         "language":"fr",
         "updatedOn":"2016-03-03T13:21:52.408Z",
         "createdOn":"2016-02-23T13:36:15.080Z",
         "version":2,
         "archived":null,
         "noHelp":false,
         "password":"$shiro1$SHA-512$500000$HQSFYGvfv6nUoTB7N4lfKQ==$50bIkOkcA140Q2RqUDpLeOgGS0VWecTpUyAwEY2Un+NHU6uz3vvd0B9KcDpvvdkO6PscxhqzWRdw0sgwH7+LOQ==",
         "blocked":false,
         "createdBy":{
            "code":"admin",
            "name":"Administrator",
            "id":1,
            "$version":2
         },
         "permissions":[

         ],
         "activateOn":null,
         "name":"Administrator",
         "expiresOn":null,
         "theme":"blue-simple",
         "id":1,
         "email":null,
         "selected":false,
         "homeAction":null,
         "group":{
            "code":"admins",
            "name":"Administrators",
            "id":1,
            "$version":1
         }
      }
   ]
}
```

I'm getting the same behavior when I try to use advanced search.

Thanks in advance for helping.

Regards,

**Comment by mrp14** [comment]
It seems to be OK with this last commit.
Thanks.
